import React, { useState } from "react";
import { Document, Page, Text, View, StyleSheet, Image, pdf } from "@react-pdf/renderer";
import { FiDownload } from "react-icons/fi";
import { formatINRCompact } from "./formatters";
import { useMPWorks } from '../hooks/useApi';
import { createBaseStyles, createExtendedStyles, getExportButtonStyles, getDisabledButtonStyles } from "./pdfUIStyles";

const baseStyles = createBaseStyles(StyleSheet);
const extendedStyles = createExtendedStyles(StyleSheet);
const styles = { ...baseStyles, ...extendedStyles };

export async function generateMPDetailPdf(data, options = {}) {
    const { fileName: fn } = options;
    const fileName = fn || `empowered_indian_mp_detail_${data.mp?.name?.replace(/\s+/g, '_') || 'mp'}_${new Date().toISOString().split('T')[0]}.pdf`;
    const docNode = <MPDetailDocument data={data} />;
    const asPdf = pdf(docNode, { author: "Empowered Indian" });
    const blob = await asPdf.toBlob();
    const url = URL.createObjectURL(blob);
    const a = window.document.createElement("a");
    a.href = url;
    a.download = fileName;
    window.document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
    return true;
}

const MPDetailDocument = ({ data }) => {
    const timestamp = new Date().toLocaleString();
    const mp = data.mp || {};
    const completedWorksData = data.completedWorks || {};
    const recommendedWorksData = data.recommendedWorks || {};
    const allocatedAmount = mp.allocatedAmount || 0;
    const totalExpenditure = mp.totalExpenditure || 0;
    const utilizationPercentage = mp.utilizationPercentage || 0;
    const completionRate = mp.completionRate || 0;
    // Get works arrays - handle both direct payload structure and nested structure
    let completedWorks = completedWorksData.works || completedWorksData.completedWorks || [];
    let recommendedWorks = recommendedWorksData.works || recommendedWorksData.recommendedWorks || [];

    // Sort completed works by finalAmount (highest first) and take top 5
    completedWorks = completedWorks
        .sort((a, b) => (b.finalAmount || 0) - (a.finalAmount || 0))
        .slice(0, 5);

    // Sort recommended works by recommendedAmount (highest first) and take top 5
    recommendedWorks = recommendedWorks
        .sort((a, b) => (b.recommendedAmount || 0) - (a.recommendedAmount || 0))
        .slice(0, 5);
    const categoryStats = {};
    completedWorks.forEach(work => {
        const category = work.workCategory || 'Normal/Others';
        if (!categoryStats[category]) {
            categoryStats[category] = { count: 0, totalCost: 0 };
        }
        categoryStats[category].count++;
        categoryStats[category].totalCost += work.finalAmount || 0;
    });

    // Group works by year
    const yearlyStats = {};
    completedWorks.forEach(work => {
        const completedDate = work.completedDate || work.date;
        const year = completedDate ? new Date(completedDate).getFullYear().toString() : 'Unknown';
        if (!yearlyStats[year]) {
            yearlyStats[year] = { count: 0, totalCost: 0 };
        }
        yearlyStats[year].count++;
        yearlyStats[year].totalCost += work.finalAmount || 0;
    });

    // Prepare yearly data for chart
    const yearlyData = Object.entries(yearlyStats).map(([year, stats]) => ({
        _id: year,
        totalAmount: stats.totalCost,
        transactionCount: stats.count
    })).sort((a, b) => a._id - b._id);

    const maxYearlyAmount = Math.max(...yearlyData.map(y => y.totalAmount || 0));

    // Top categories for insights
    const topCategories = Object.entries(categoryStats)
        .sort(([, a], [, b]) => b.totalCost - a.totalCost)
        .slice(0, 3);

    return (
        <Document>
            <Page size="A4" style={styles.page}>
                <View style={styles.header}>
                    <View style={styles.headerGradient} />
                    <View style={styles.headerAccent} />
                    <View style={styles.headerRow}>
                        <Image style={styles.logo} src="https://avatars.githubusercontent.com/u/230681844?s=200&v=4" />
                        <View style={styles.titleBlock}>
                            <Text style={styles.title}>Empowered Indian</Text>
                            <Text style={styles.subtitle}>MP Performance Report</Text>
                            <Text style={[styles.smallText, { marginTop: 2 }]}>Transparent • Data-Driven • Impactful</Text>
                        </View>
                        <View style={{ width: '140px' }}>
                            <Text style={styles.timestamp}>{timestamp}</Text>
                            <Text style={styles.generatedBy}>Generated by Empowered Indian</Text>
                        </View>
                    </View>
                </View>

                <View style={styles.content}>
                    {/* MP Info Header */}
                    <View style={styles.summary}>
                        <View style={styles.summaryHeader}>
                            <View style={styles.summaryIcon} />
                            <Text style={styles.summaryTitle}>{mp.name || 'MP Name'}</Text>
                        </View>
                        <Text style={[styles.smallText, { marginBottom: 8 }]}>
                            {mp.constituency || 'Constituency'} • {mp.state || 'State'} • {mp.house || 'House'}
                        </Text>

                        <View style={styles.summaryGrid}>
                            <View style={styles.summaryColumn}>
                                <View style={styles.summaryMetric}>
                                    <Text style={styles.summaryMetricLabel}>Allocated Amount</Text>
                                    <Text style={styles.summaryMetricValue}>{formatINRCompact(allocatedAmount)}</Text>
                                    <Text style={styles.summaryMetricSub}>Total MPLADS allocation</Text>
                                </View>
                                <View style={styles.summaryMetric}>
                                    <Text style={styles.summaryMetricLabel}>Total Expenditure</Text>
                                    <Text style={styles.summaryMetricValue}>{formatINRCompact(totalExpenditure)}</Text>
                                    <Text style={styles.summaryMetricSub}>
                                        {utilizationPercentage.toFixed(1)}% fund utilization
                                    </Text>
                                </View>
                            </View>

                            <View style={styles.summaryColumn}>
                                <View style={styles.summaryMetric}>
                                    <Text style={styles.summaryMetricLabel}>Works Completed</Text>
                                    <Text style={styles.summaryMetricValue}>{completedWorks.length}</Text>
                                    <Text style={styles.summaryMetricSub}>
                                        {completionRate.toFixed(1)}% completion rate
                                    </Text>
                                </View>
                                <View style={styles.summaryMetric}>
                                    <Text style={styles.summaryMetricLabel}>Works Recommended</Text>
                                    <Text style={styles.summaryMetricValue}>{recommendedWorks.length}</Text>
                                    <Text style={styles.summaryMetricSub}>{mp.pendingWorks || 0} pending works</Text>
                                </View>
                            </View>
                        </View>
                    </View>

                    {/* Expenditure Chart */}
                    {yearlyData.length > 0 && (
                        <View style={styles.chart}>
                            <View style={styles.chartHeader}>
                                <View style={styles.chartIcon} />
                                <Text style={styles.chartTitle}>Yearly Expenditure Trend</Text>
                            </View>
                            <View style={styles.chartContainer}>
                                {yearlyData.map((yearData, i) => {
                                    const amount = yearData.totalAmount || 0;
                                    const height = maxYearlyAmount > 0 ? Math.max(10, (amount / maxYearlyAmount) * 100) : 10;
                                    return (
                                        <View key={i} style={styles.chartBar}>
                                            <View style={[styles.chartBarFill, { height }]}>
                                                <Text style={styles.chartValue}>{formatINRCompact(amount)}</Text>
                                            </View>
                                            <Text style={styles.chartLabel}>{yearData._id}</Text>
                                        </View>
                                    );
                                })}
                            </View>
                        </View>
                    )}

                    {/* Yearly Breakdown */}
                    {yearlyData.length > 0 && (
                        <View style={styles.yearlyBreakdown}>
                            <View style={styles.yearlyHeader}>
                                <View style={styles.yearlyIcon} />
                                <Text style={styles.yearlyTitle}>Yearly Performance Breakdown</Text>
                            </View>
                            {yearlyData.map((yearData, i) => (
                                <View key={i} style={styles.yearlyItem}>
                                    <Text style={styles.yearlyYear}>{yearData._id}</Text>
                                    <View>
                                        <Text style={styles.yearlyStats}>
                                            {yearData.transactionCount} works • {formatINRCompact(yearData.totalAmount)}
                                        </Text>
                                    </View>
                                </View>
                            ))}
                        </View>
                    )}

                    {/* Category Breakdown */}
                    {Object.keys(categoryStats).length > 0 && (
                        <View style={styles.works}>
                            <View style={styles.worksHeader}>
                                <View style={styles.worksIcon} />
                                <Text style={styles.worksTitle}>Work Categories Breakdown</Text>
                            </View>
                            {topCategories.map(([category, stats], i) => (
                                <View key={i} style={styles.workItem}>
                                    <Text style={styles.workTitle}>{category}</Text>
                                    <Text style={styles.workDescription}>
                                        {stats.count} works • Total cost: {formatINRCompact(stats.totalCost)}
                                    </Text>
                                    <View style={styles.workMeta}>
                                        <Text style={styles.workMetaItem}>
                                            Average: {formatINRCompact(stats.totalCost / stats.count)}
                                        </Text>
                                        <Text style={styles.workMetaItem}>
                                            {((stats.totalCost / totalExpenditure) * 100).toFixed(1)}% of total
                                        </Text>
                                    </View>
                                </View>
                            ))}
                        </View>
                    )}

                    {/* Completed Works */}
                    {completedWorks.length > 0 && (
                        <View style={styles.works}>
                            <View style={styles.worksHeader}>
                                <View style={styles.worksIcon} />
                                <Text style={styles.worksTitle}>Top 5 Completed Works by Amount ({completedWorks.length})</Text>
                            </View>
                            {completedWorks.map((work, i) => (
                                <View key={i} style={styles.workItem}>
                                    <Text style={styles.workTitle}>{work.workCategory || 'Work'}</Text>
                                    <Text style={styles.workDescription}>{work.workDescription || 'No description'}</Text>
                                    <View style={styles.workMeta}>
                                        <Text style={styles.workMetaItem}>
                                            Completed: {new Date(work.completedDate || work.date).toLocaleDateString()}
                                        </Text>
                                        <Text style={styles.workMetaItem}>
                                            Amount: {formatINRCompact(work.finalAmount || 0)}
                                        </Text>
                                    </View>
                                </View>
                            ))}
                        </View>
                    )}

                    {/* Recommended Works */}
                    {recommendedWorks.length > 0 && (
                        <View style={styles.works}>
                            <View style={styles.worksHeader}>
                                <View style={styles.worksIcon} />
                                <Text style={styles.worksTitle}>Top 5 Recommended Works by Amount ({recommendedWorks.length})</Text>
                            </View>
                            {recommendedWorks.map((work, i) => (
                                <View key={i} style={styles.workItem}>
                                    <Text style={styles.workTitle}>{work.workCategory || 'Work'}</Text>
                                    <Text style={styles.workDescription}>{work.workDescription || 'No description'}</Text>
                                    <View style={styles.workMeta}>
                                        <Text style={styles.workMetaItem}>
                                            Recommended: {new Date(work.recommendationDate || work.date).toLocaleDateString()}
                                        </Text>
                                        <Text style={styles.workMetaItem}>
                                            Amount: {formatINRCompact(work.recommendedAmount || work.totalPaid || 0)}
                                        </Text>
                                    </View>
                                </View>
                            ))}
                            {recommendedWorks.length === 5 && (
                                <Text style={[styles.smallText, { textAlign: 'center', marginTop: 8 }]}>
                                    Showing top 5 works by recommended amount
                                </Text>
                            )}
                        </View>
                    )}
                </View>

                <View style={styles.footer}>
                    <View style={styles.footerLeft}>
                        <Image style={styles.footerLogo} src="https://avatars.githubusercontent.com/u/230681844?s=200&v=4" />
                        <Text style={[styles.smallText, { marginTop: 2, fontSize: 7 }]}>
                            * Data sourced from official MPLADS records. For latest updates, visit empoweredindian.in
                        </Text>
                    </View>
                </View>
            </Page>
        </Document>
    );
};

const ExportMPsDetailAsPdf = ({ mpData }) => {
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);

    const mpComWorksParams = {
        state: mpData?.state || '',
        constituency: mpData?.constituency || '',
        status: 'completed'
    };

    const mpRecWorksParams = {
        state: mpData?.state || '',
        constituency: mpData?.constituency || '',
        status: 'recommended'
    };

    const completedWorks = useMPWorks(mpData.id, mpComWorksParams);
    const recommendedWorks = useMPWorks(mpData.id, mpRecWorksParams);

    const data = {
        mp: mpData,
        completedWorks: completedWorks?.data?.data ? completedWorks?.data?.data : completedWorks?.data,
        recommendedWorks: recommendedWorks?.data?.data ? recommendedWorks?.data?.data : recommendedWorks?.data
    }

    console.log("ExportMPsDetailAsPdf mpData:", data);

    if (!data) {
        return (
            <button
                disabled
                style={getDisabledButtonStyles()}
            >
                <FiDownload /> No data to export
            </button>
        );
    }

    const handleClick = async () => {
        setError(null);
        setLoading(true);
        try {
            await generateMPDetailPdf(data, {
                fileName: `empowered_indian_mp_detail_${data.mp?.name?.replace(/\s+/g, '_') || 'mp'}_${new Date().toISOString().split('T')[0]}.pdf`
            });
        } catch (e) {
            console.error("PDF generation failed", e);
            setError("Failed to generate PDF");
        } finally {
            setLoading(false);
        }
    };

    return (
        <button
            onClick={handleClick}
            disabled={loading}
            style={getExportButtonStyles(loading, error)}
        >
            <FiDownload />
            {loading ? "Generating PDF..." : error ? "Export Failed" : "Download Report"}
        </button>
    );
};

export default ExportMPsDetailAsPdf;

// Test function to verify PDF generation with the provided payload
export async function testMPDetailPdfGeneration() {
    const testPayload = {
        "mp": {
            "id": "68c5212b598546b226615b60",
            "name": "SH Vijay Pal Singh Tomar",
            "constituency": "Sitting Rajya Sabha",
            "state": "Uttar Pradesh",
            "house": "Rajya Sabha",
            "allocatedAmount": 73563957.11,
            "totalExpenditure": 72318907,
            "utilizationPercentage": 98.30752700247177,
            "completedWorksCount": 22,
            "recommendedWorksCount": 92,
            "completedWorksValue": 19044963,
            "inProgressPayments": 53273944,
            "paymentGapPercentage": 73.66530581000069,
            "completionRate": 19.298245614035086,
            "pendingWorks": 70,
            "unspentAmount": 1245050.1099999994,
            "totalRecommendedAmount": 54317600,
            "name_hi": "SH Vijay Pal Singh Tomar",
            "constituency_hi": "Sitting Rajya Sabha",
            "state_hi": "Uttar Pradesh"
        },
        "completedWorks": {
            "works": [
                {
                    "_id": "68c5212f598546b2266479d4",
                    "mpName": "SH Vijay Pal Singh Tomar",
                    "mp_id": "68c5212b598546b226616061",
                    "house": "Rajya Sabha",
                    "state": "Uttar Pradesh",
                    "constituency": "Sitting Rajya Sabha",
                    "workCategory": "Normal/Others",
                    "workId": 31542,
                    "ida": "HAPUR(DISTRICT MAGISTRATE HAPUR_IDA)",
                    "workDescription": "Black Road Construction Work : \nFrom Junior High School to Hasupur South Main Road. Approximately 500 m. Estimated cost 15 lakhs.",
                    "completedDate": "2025-07-15T00:00:00.000Z",
                    "hasImage": true,
                    "averageRating": null,
                    "finalAmount": 1479139,
                    "lsTerm": null,
                    "createdAt": "2025-09-13T07:45:51.372Z",
                    "status": "completed",
                    "date": "2025-07-15T00:00:00.000Z"
                },
                {
                    "_id": "68c5212f598546b2266483ec",
                    "mpName": "SH Vijay Pal Singh Tomar",
                    "mp_id": "68c5212b598546b226616061",
                    "house": "Rajya Sabha",
                    "state": "Uttar Pradesh",
                    "constituency": "Sitting Rajya Sabha",
                    "workCategory": "Normal/Others",
                    "workId": 48510,
                    "ida": "BULANDSHAHR(DISTRICT MAGISTRATE BULANDSHAHR_IDA)",
                    "workDescription": "Building construction and\ngate beautification : Rajju Bhaiya Sainik Vidya Mandir at Khandwaya, Khurja Road. Estimated cost is approximately Rs 20 lakh.",
                    "completedDate": "2024-06-30T00:00:00.000Z",
                    "hasImage": true,
                    "averageRating": null,
                    "finalAmount": 1995556,
                    "lsTerm": null,
                    "createdAt": "2025-09-13T07:45:51.374Z",
                    "status": "completed",
                    "date": "2024-06-30T00:00:00.000Z"
                },
                {
                    "_id": "68c5212f598546b226647baf",
                    "mpName": "SH Vijay Pal Singh Tomar",
                    "mp_id": "68c5212b598546b226616061",
                    "house": "Rajya Sabha",
                    "state": "Uttar Pradesh",
                    "constituency": "Sitting Rajya Sabha",
                    "workCategory": "Normal/Others",
                    "workId": 40861,
                    "ida": "HAPUR(DISTRICT MAGISTRATE HAPUR_IDA)",
                    "workDescription": "Shed, bench in cremation ground\nand manufacturing of tiles : In the cremation ground of village Parpa. Estimated cost is around Rs 10 lakh.",
                    "completedDate": "2024-06-10T00:00:00.000Z",
                    "hasImage": true,
                    "averageRating": null,
                    "finalAmount": 979704,
                    "lsTerm": null,
                    "createdAt": "2025-09-13T07:45:51.372Z",
                    "status": "completed",
                    "date": "2024-06-10T00:00:00.000Z"
                },
                {
                    "_id": "68c5212f598546b226647c9b",
                    "mpName": "SH Vijay Pal Singh Tomar",
                    "mp_id": "68c5212b598546b226616061",
                    "house": "Rajya Sabha",
                    "state": "Uttar Pradesh",
                    "constituency": "Sitting Rajya Sabha",
                    "workCategory": "Normal/Others",
                    "workId": 40862,
                    "ida": "HAPUR(DISTRICT MAGISTRATE HAPUR_IDA)",
                    "workDescription": "building construction work : Independent India Inter College Building Construction Work. Estimated cost is around Rs 10 lakh",
                    "completedDate": "2024-06-10T00:00:00.000Z",
                    "hasImage": true,
                    "averageRating": null,
                    "finalAmount": 994627,
                    "lsTerm": null,
                    "createdAt": "2025-09-13T07:45:51.372Z",
                    "status": "completed",
                    "date": "2024-06-10T00:00:00.000Z"
                },
                {
                    "_id": "68c5212f598546b2266476cd",
                    "mpName": "SH Vijay Pal Singh Tomar",
                    "mp_id": "68c5212b598546b226616061",
                    "house": "Rajya Sabha",
                    "state": "Uttar Pradesh",
                    "constituency": "Sitting Rajya Sabha",
                    "workCategory": "Normal/Others",
                    "workId": 31547,
                    "ida": "HAPUR(DISTRICT MAGISTRATE HAPUR_IDA)",
                    "workDescription": "High mast light : • On the way in front of the meeting of late Mahavir Singh.\n• On the road in front of the wedding procession near Pramod Inspector's house.\n• On the road in front of Harendra's house.\n• S.o.d.on the way outside Kanya Inter Vidyalaya.\n• On the way outside the big Shiva temple.",
                    "completedDate": "2024-06-06T00:00:00.000Z",
                    "hasImage": true,
                    "averageRating": null,
                    "finalAmount": 699103,
                    "lsTerm": null,
                    "createdAt": "2025-09-13T07:45:51.371Z",
                    "status": "completed",
                    "date": "2024-06-06T00:00:00.000Z"
                },
                {
                    "_id": "68c5212f598546b226648514",
                    "mpName": "SH Vijay Pal Singh Tomar",
                    "mp_id": "68c5212b598546b226616061",
                    "house": "Rajya Sabha",
                    "state": "Uttar Pradesh",
                    "constituency": "Sitting Rajya Sabha",
                    "workCategory": "Normal/Others",
                    "workId": 48511,
                    "ida": "BULANDSHAHR(DISTRICT MAGISTRATE BULANDSHAHR_IDA)",
                    "workDescription": "C.C. construction work: From Harendra Tomar's house to Ajit Raghav's house. Estimated cost is approximately Rs 10 lakh.",
                    "completedDate": "2024-06-06T00:00:00.000Z",
                    "hasImage": true,
                    "averageRating": null,
                    "finalAmount": 987054,
                    "lsTerm": null,
                    "createdAt": "2025-09-13T07:45:51.375Z",
                    "status": "completed",
                    "date": "2024-06-06T00:00:00.000Z"
                }
            ],
            "pagination": {
                "page": 1,
                "limit": 50,
                "total": 22,
                "totalCount": 22,
                "pages": 1,
                "currentPage": 1,
                "hasNext": false,
                "hasPrev": false
            },
            "summary": {
                "totalCost": 19044963,
                "totalWorks": 22
            },
            "filters": {
                "status": "completed",
                "category": "all"
            }
        },
        "recommendedWorks": {
            "works": [
                {
                    "_id": "68c52130598546b226666c3c",
                    "mpName": "SH Vijay Pal Singh Tomar",
                    "house": "Rajya Sabha",
                    "state": "Uttar Pradesh",
                    "constituency": "Sitting Rajya Sabha",
                    "workCategory": "Normal/Others",
                    "workId": 112098,
                    "ida": "MEERUT(DISTRICT MAGISTRATE MEERUT_IDA)",
                    "workDescription": "Yeh kaary vikas khand rajpura se hoga, kaary High Mast light, Bhagwaanpur Chittawan sthaan sw om prakash sharma master ji ke ghar ke samane tirahe per.",
                    "recommendationDate": "2024-02-22T00:00:00.000Z",
                    "recommendedAmount": 140000,
                    "lsTerm": null,
                    "hasPayments": true,
                    "totalPaid": 139729,
                    "paymentCount": 2,
                    "status": "recommended",
                    "date": "2024-02-22T00:00:00.000Z"
                },
                {
                    "_id": "68c52130598546b226666c3b",
                    "mpName": "SH Vijay Pal Singh Tomar",
                    "house": "Rajya Sabha",
                    "state": "Uttar Pradesh",
                    "constituency": "Sitting Rajya Sabha",
                    "workCategory": "Normal/Others",
                    "workId": 112062,
                    "ida": "MEERUT(DISTRICT MAGISTRATE MEERUT_IDA)",
                    "workDescription": "yah kaary vikaas khand rajpura se hoga. kaary RCC v Rubber mait gram ward no 32, kailaash prakaash stediyam ke baasketabaal traik par nirmaan karavaana hai, anumaanit laagat 08 laakh 20 hajaar Rupees lagabhag",
                    "recommendationDate": "2024-02-22T00:00:00.000Z",
                    "recommendedAmount": 820000,
                    "lsTerm": null,
                    "hasPayments": true,
                    "totalPaid": 797295,
                    "paymentCount": 2,
                    "status": "recommended",
                    "date": "2024-02-22T00:00:000Z"
                },
                {
                    "_id": "68c52130598546b226666bda",
                    "mpName": "SH Vijay Pal Singh Tomar",
                    "house": "Rajya Sabha",
                    "state": "Uttar Pradesh",
                    "constituency": "Sitting Rajya Sabha",
                    "workCategory": "Normal/Others",
                    "workId": 110204,
                    "ida": "MEERUT(DISTRICT MAGISTRATE MEERUT_IDA)",
                    "workDescription": "kaary C.C. Nirman Kaary gram kau Khas, Chauiya ki Puliya se damar sadak tak lgbhag 130 meter anumanit lagat 11 lakh rupees. yeh kaary vikas khand rajpura sansthaa se hoga.",
                    "recommendationDate": "2024-02-20T00:00:00.000Z",
                    "recommendedAmount": 1100000,
                    "lsTerm": null,
                    "hasPayments": true,
                    "totalPaid": 1087960,
                    "paymentCount": 2,
                    "status": "recommended",
                    "date": "2024-02-20T00:00:00.000Z"
                },
                {
                    "_id": "68c52130598546b2266665f3",
                    "mpName": "SH Vijay Pal Singh Tomar",
                    "house": "Rajya Sabha",
                    "state": "Uttar Pradesh",
                    "constituency": "Sitting Rajya Sabha",
                    "workCategory": "Normal/Others",
                    "workId": 70659,
                    "ida": "MEERUT(DISTRICT MAGISTRATE MEERUT_IDA)",
                    "workDescription": "Interlocking tiles Construction work : From Kinanagar road towards Mule/Madan's house. Estimated cost Rs 10.00 lakh approx.",
                    "recommendationDate": "2023-12-28T00:00:00.000Z",
                    "recommendedAmount": 1000000,
                    "lsTerm": null,
                    "hasPayments": true,
                    "totalPaid": 996954,
                    "paymentCount": 2,
                    "status": "recommended",
                    "date": "2023-12-28T00:00:00.000Z"
                },
                {
                    "_id": "68c52130598546b2266665f4",
                    "mpName": "SH Vijay Pal Singh Tomar",
                    "house": "Rajya Sabha",
                    "state": "Uttar Pradesh",
                    "constituency": "Sitting Rajya Sabha",
                    "workCategory": "Normal/Others",
                    "workId": 70660,
                    "ida": "MEERUT(DISTRICT MAGISTRATE MEERUT_IDA)",
                    "workDescription": "High Mast Light : • In the women's park.\n• On the roads near the ground of Ram Krishna Inter College.\n• On the way to gym and wedding procession.\n• On the roads near the hut temple.",
                    "recommendationDate": "2023-12-28T00:00:00.000Z",
                    "recommendedAmount": 560000,
                    "lsTerm": null,
                    "hasPayments": true,
                    "totalPaid": 558999,
                    "paymentCount": 2,
                    "status": "recommended",
                    "date": "2023-12-28T00:00:00.000Z"
                },
                {
                    "_id": "68c52130598546b2266665f2",
                    "mpName": "SH Vijay Pal Singh Tomar",
                    "house": "Rajya Sabha",
                    "state": "Uttar Pradesh",
                    "constituency": "Sitting Rajya Sabha",
                    "workCategory": "Normal/Others",
                    "workId": 70658,
                    "ida": "MEERUT(DISTRICT MAGISTRATE MEERUT_IDA)",
                    "workDescription": "Interlocking tiles\nConstruction work : From Mahendra Fauji's house to Sonu's house. Length 115 m. Estimated cost Rs. 07.46 lakh approx.",
                    "recommendationDate": "2023-12-28T00:00:00.000Z",
                    "recommendedAmount": 746000,
                    "lsTerm": null,
                    "hasPayments": true,
                    "totalPaid": 739645,
                    "paymentCount": 2,
                    "status": "recommended",
                    "date": "2023-12-28T00:00:00.000Z"
                }
            ],
            "pagination": {
                "page": 1,
                "limit": 50,
                "total": 92,
                "totalCount": 92,
                "pages": 2,
                "currentPage": 1,
                "hasNext": true,
                "hasPrev": false
            },
            "summary": {
                "totalCost": 54317600,
                "totalWorks": 92
            },
            "filters": {
                "status": "recommended",
                "category": "all"
            }
        }
    };

    try {
        console.log("Testing MP Detail PDF generation with payload...");
        console.log("Completed works amounts:", testPayload.completedWorks.works.map(w => w.finalAmount));
        console.log("Recommended works amounts:", testPayload.recommendedWorks.works.map(w => w.recommendedAmount));

        const result = await generateMPDetailPdf(testPayload, {
            fileName: `test_mp_detail_${testPayload.mp.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`
        });
        console.log("PDF generation test completed successfully:", result);
        return result;
    } catch (error) {
        console.error("PDF generation test failed:", error);
        throw error;
    }
}